source 'http://rubygems.org'

gem 'rails', '3.1.0'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails', "  ~> 3.1.0"
  gem 'coffee-rails', "~> 3.1.0"
  gem 'uglifier'
end

gem 'jquery-rails'

# CAS Gems
#gem 'rubycas-client'
gem 'rubycas-client-rails'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

gem 'will_paginate', '~> 3.0.0'
gem "paperclip", "~> 2.4"
gem "friendly_id", "~> 4.0.0.beta8"
gem 'acts-as-taggable-on', '~>2.1.0'
# gem "RedCloth"
gem 'bluecloth', "~> 2.0"

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

group :test do
  # Pretty printed test output
  gem 'turn', :require => false
end
